# Default settings for Report Formats
# ============================================
# This contains the default for different settings.

md:
  type: md
  extension: '.md'
  width: 100
  keep_soft_breaks: true
  use_references: false

html:
  type: html
  extension: .html
  compress: false
  head_begin: |+
    <!DOCTYPE html><html>
    <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  head_end: |+
    <meta name="HandheldFriendly" content="true" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <meta name="generator" content="alinex-codedoc" />
    </head>
  body_begin: |+
    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topnav" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://alinex.github.io/" onmouseover="logo.src='https://alinex.github.io/images/Alinex-200.png'" onmouseout="logo.src='https://alinex.github.io/images/Alinex-black-200.png'">
              <img name="logo" src="https://alinex.github.io/images/Alinex-black-200.png" width="150" title="Alinex Homepage">
            </a>
            <img class="preload" src="https://alinex.github.io/images/Alinex-200.png" aria-hidden="true">
          </div>
          <div id="topnav" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="https://alinex.github.io/blog" class="btn btn-primary">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Blog
                </a></li>
              <li><a href="https://alinex.github.io/develop" class="btn btn-primary">
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Develop
                </a></li>
              <li><a href="https://alinex.github.io/code.html" class="btn btn-warning">
                  <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Code
                </a></li>
            </ul>
            <form class="navbar-form navbar-right">
              <input name="q" type="text" class="form-control" placeholder="Search...">
            </form>
            <ul class="nav sidebar-to-top">
              {{#iterate pages}}
                {{#if value.active}}
                  <li class="active level{{value.depth}}">
                    <a href="{{value.url}}" title="{{value.title}} ({{value.path}})" class="btn btn-warning">{{value.link}} <span class="sr-only">(current)</span></a>
                  </li>
                {{else}}
                  <li class="level{{value.depth}}">
                    <a href="{{value.url}}" title="{{value.title}} ({{value.path}})" class="btn btn-primary">{{value.link}}</a>
                  </li>
                {{/if}}
              {{/iterate}}
            </ul>
          </div>
        </div>
      </nav>

      <div class="navbar-spacer"></div>

      <div class="container-fluid">
        <div class="row">

          <div class="col-sm-9 col-sm-push-3 main">
            {{include codedoc-search-result}}
            <main>
  body_end: |+
            </main>
          </div>
          <div class="col-sm-3 col-cm-pull-9 sidebar">
            <ul class="nav nav-sidebar">
              <li class="header">
                <a href="{{pages.0.url}}">{{moduleName}}</a>
              </li>
              {{#iterate pages}}
                {{#if value.active}}
                  <li class="active level{{value.depth}}">
                    <a href="{{value.url}}" title="{{value.title}} ({{value.path}})">{{value.link}} <span class="sr-only">(current)</span></a>
                  </li>
                {{else}}
                  <li class="level{{value.depth}}">
                    <a href="{{value.url}}" title="{{value.title}} ({{value.path}})">{{value.link}}</a>
                  </li>
                {{/if}}
              {{/iterate}}
            </ul>
          </div>

        </div>
      </div>

      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
      <script type="text/javascript"><!--
      $(".table-of-contents").bind("mouseleave", function(event) { $(".table-of-contents").scrollTop(0); });
      //--></script>
    </body>
  style:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
    #  included inline in the moment
    #  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/github.min.css
    - report/default.css
    - codedoc/default.css
